language: node_js
node_js:
- '4'
- '5'
- '6'
sudo: false
branches:
  only:
  - master
  - develop
notifications:
  email:
  - otaviokk@gmail.com
script: npm run validate
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: otaviokk@gmail.com
  api_key:
    secure: PNd0fmRE9v2qfMauQGHy94kDWXUUmFzztlfIhohWKuUy3IAgnM2+d0+CiwQ0J6M1VLQw0p4dUeA9XLU3YAwBEVji03VNzCgAS9IeKUEwirjiyqdKturr0YOKyAb1MW0cFULXCMZbjHuExblMJXf4v6k7W5M67xaW1H0jshkw1HtRUbNuZU5v91OXOlDKIbTLofFM2cbU/uPoryGSS8dV58E622G7PWqjdG1+GmiLmNl/AbrWqfKRzqwSZyDFzHVW6yY6utn5bIzS7sjvE/8cEoLUixrLqiXVJfSytpV5Bd1bKkrM41ZQCKLaqBXTyIQtjtWXOIAvldajfJleharHZcI6QwRzYek1lid4TgJez+AyPy6EjmwrAOXhjvxJ5rjjI+W6gSh2MKr/uZW2jJa6RwfgxH5bvCNoObok6Ueb68rTgmOpWj5Ze4TxZV7ua0XHYyn6tbFACeexEqtXEnH5T99aicw4Lzxm+PFSwQLI5xPwDU0a7fRA8JeevmFcxNHFO/2OMxFtqkeI745mnWEGJXAQlXCM+vrcyAo5uaFs17ufff8cUPXW9QXe6Y0W07G56dnNJWuGDkdbOO3l98NNgVuSkYwR+KvzZNyZPFUSFCn8caIZK+qhI5MN2Xytfp64PMhoevoLi1WHm1QdlkyTU0kUMTsronhZ6A0IqxZmJZ8=
  on:
    tags: true
    repo: otaviosoares/seneca-servicebus-transport
cache:
  directories: node_modules
